### ISSUE TITLE
Feature request: Specify alternative dot directory

### ISSUE THREAD

**Issue by carlsonp** [SoftwareIntrospectionLab/MininGit#153]
I'm trying to run MininGit (cvsanaly2) through an Apache user in Linux that is restricted and doesn't have much in the way of permissions and a home directory.  Right now I'm getting an error:

Traceback (most recent call last):
  File "/usr/local/bin/cvsanaly2", line 5, in <module>
    pkg_resources.run_script('cvsanaly==2.4', 'cvsanaly2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/EGG-INFO/scripts/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/main.py", line 509, in main
    _parse_log(path or uri, repo, parser, reader, config, db)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/main.py", line 154, in _parse_log
    parser.end()
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/Parser.py", line 63, in end
    self.handler.end()  
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/DBProxyContentHandler.py", line 68, in end
    self.db_handler.repository(self.repo_uri)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/DBContentHandler.py", line 109, in repository
    self.cache_file = os.path.join(cvsanaly_cache_dir(), filename)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/utils.py", line 163, in cvsanaly_cache_dir
    cache_dir = os.path.join(cvsanaly_dot_dir(), 'cache')
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly-2.4-py2.7.egg/pycvsanaly2/utils.py", line 142, in cvsanaly_dot_dir
    dot_dir = os.path.join(os.environ.get('HOME'), '.cvsanaly2')
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Essentially, it's failing creating the hidden directory for storage of files.  It would be great if I could specify via a parameter an alternative location to save these files or if it could just continue on without needing this (just save them to a temporary directory or something).

**Comment by linzhp** [comment]
This is an unusual use case which we did not have resource to support. It would be great if you could fix it and send a pull request.
