### ISSUE TITLE
Errors in CommitsLOC (IndexError: list index out of range)

### ISSUE THREAD

**Issue by hennar** [SoftwareIntrospectionLab/MininGit#160]
The commits_line table is empty at the point the software exits. Any ideas what I can do to try and pinpoint the problem?

Afaik, the repository I'm trying to read is currently a Git repository, but it's been converted from subversion (and before that from cvs to subversion) by the project itself.

Executing extension CommitsLOC
Traceback (most recent call last):
  File "/usr/local/bin/miningit", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/main.py", line 539, in main
    emg.run_extensions(repo, path or uri, db)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/ExtensionsManager.py", line 133, in run_extensions
    self.run_extension(name, extension, repo, uri, db)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/ExtensionsManager.py", line 76, in run_extension
    extension.run(repo, uri, db)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/extensions/CommitsLOC.py", line 299, in run
    counter = create_line_counter_for_repository(repo, uri)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/extensions/CommitsLOC.py", line 209, in create_line_counter_for_repository
    return counter(repo, uri)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/extensions/CommitsLOC.py", line 171, in **init**
    c.run(parser_out_func=self.__parse_line)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/Command.py", line 256, in run
    timeout)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/Command.py", line 218, in _run_with_callbacks
    return self._read_from_pipes(stdin, out_func, err_func, timeout)
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/Command.py", line 159, in _read_from_pipes
    out_data_cb[0](out_chunk, out_data_cb[1])
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/Command.py", line 195, in out_cb
    parser_out_func(out_data[:pos + 1])
  File "/usr/local/lib/python2.7/dist-packages/pycvsanaly2/extensions/CommitsLOC.py", line 192, in __parse_line
    self.rev = line.split(None, 1)[0]
IndexError: list index out of range
You have new mail in /var/mail/hennar
hennar@asja:~/git/core$ miningit -u xxx -p xxx -d t_miningit --extensions=FileTypes,CommitsLOC

**Comment by linzhp** [comment]
It could be the incompatibility of different git versions, which return slightly different format in their outputs, making the parsing broken sometimes. Currently, MiniGit is tested from Git 1.7.4 to 1.7.9. If you are using other versions, you are encouraged to make MiniGit supporting them.
