### ISSUE TITLE
trouble with foreign key constraints

### ISSUE THREAD

**Issue by supertri** [SoftwareIntrospectionLab/MininGit#24]
Cvsanaly crashes when I try to run it because the foreign key constraints do not hold:

Parsing log for /Users/supertri/repos/CloudFlare-CPanel (git)
Traceback (most recent call last):
  File "/usr/local/bin/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/Library/Python/2.6/site-packages/pycvsanaly2/main.py", line 328, in main
    parser.end ()
  File "/Library/Python/2.6/site-packages/pycvsanaly2/Parser.py", line 62, in end
    self.handler.end ()  
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBProxyContentHandler.py", line 83, in end
    self.db_handler.commit (item)
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBContentHandler.py", line 599, in commit
    file_id = self.**action_add (path, prefix, log)
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBContentHandler.py", line 397, in __action_add
    parent_id = self.__get_file_for_path (parent_path, log.id)[0]
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBContentHandler.py", line 387, in __get_file_for_path
    return ensure_path (path, commit_id)
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBContentHandler.py", line 347, in ensure_path
    node_id = self.__add_new_file_and_link (token, parent, commit_id)
  File "/Library/Python/2.6/site-packages/pycvsanaly2/DBContentHandler.py", line 169, in __add_new_file_and_link
    self.cursor.execute (statement (DBFileLink.__insert**, self.db.place_holder), (dblink.id, dblink.parent, dblink.child, dblink.commit_id))
  File "build/bdist.macosx-10.6-universal/egg/MySQLdb/cursors.py", line 174, in execute
  File "build/bdist.macosx-10.6-universal/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`cvsanaly_dev`.`file_links`, CONSTRAINT `file_links_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `files` (`id`))')

I am using mysql version 5.5.8; I believe support for actually checking foreign key constraints in mysql was a fairly recent addition.

**Comment by cflewis** [comment]
cvsanaly doesn't make InnoDB tables by default, it doesn't specify the table type. You need InnoDB tables for foreign keys to be enforced. The default on MySQL 5 is MyISAM. Either you, or your MySQL configuration, is changing it to InnoDB. You will need to change this.

I would expect cvsanaly was never tested with foreign keys actually enforced. Change your configuration to MyISAM and it will work.

See http://dev.mysql.com/doc/refman/5.0/en/storage-engines.html

**Comment by supertri** [comment]
I think this is also a bug -- if foreign key constraints do not hold than something is awry.
