### ISSUE TITLE
UTF-8 conversion not working correctly

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#29]
`git show 87e3553f069ad206307fcf9b553c41aa93fca384:docs/manual/upgrading.html.pt-br` for Apache httpd gives a file, but it wasn't inserted into Content.

Expect the Python Unicode conversion failed, so was ignored by 

```
if finished_job.get_file_contents() is not None:
```

Need to try and fix this.

**Comment by cflewis** [comment]
The Python conversion to UTF-8 did fail, but it's not clear there's anything I can do about it. Googling indicates the files missed might even be corrupted.

```
>>> s.encode("utf-16")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 488: ordinal not in range(128)
>>> v = unicode(s, "utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 488: invalid continuation byte
```

There are lots of files that just don't exist in Content right now.

Workaround: Have content ignore "is not None" and just have it count the number of lines anyway. Attempting to store stuff in the db without an encoding is doomed to failure, but we get what we need this way.

Other possibilities is that the Git show fails because the file path is wrong. This might get fixed when we start working on file paths.

**Comment by cflewis** [comment]
Closing this, Content now doesn't try to change things into unicode before counting the number of lines.
