### ISSUE TITLE
Patches doesn't die gracefully

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#62]
Patches doesn't handle death gracefully, which I think hangs the whole process. Mostly an issue for SVN.

```
Error running show command: Command '['svn', 'diff', '-c', u'18', u'http://bwapi.googlecode.com/svn']' returned non-zero exit status 1
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/tomcat6/.jenkins/jobs/cvsanaly_svn/workspace/pycvsanaly2/extensions/Jobs.py", line 51, in _job_thread
    job.run(repo, repo_uri)
  File "/usr/share/tomcat6/.jenkins/jobs/cvsanaly_svn/workspace/pycvsanaly2/extensions/Patches.py", line 61, in run
    self.get_patch_for_commit()
  File "/usr/share/tomcat6/.jenkins/jobs/cvsanaly_svn/workspace/pycvsanaly2/extensions/Patches.py", line 54, in get_patch_for_commit
    self.data = self.data.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by cflewis** [comment]
Added some error handling for patches, closed by f9014cd975927d54897b39c52a3fa2c4f092c45e
