### ISSUE TITLE
Ignore non-existent tables during backout

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#80]
It would be more friendly to skip non-existent tables and continue instead of raising an exception and exiting the whole program. I looked into it, and found that the only message we could get is something like "(1146, "Table 'cvsanaly.patches' doesn't exist")". Besides pattern-matching the error message from mysql, is there a better way?

**Comment by cflewis** [comment]
It does do that for sqlite (I think). Can you get me a full stack trace?

**Comment by linzhp** [comment]
Traceback (most recent call last):
  File "/home/linzhp/python/cvsanaly/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/main.py", line 360, in main
    emg.backout_extensions(repo, path or uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/ExtensionsManager.py", line 102, in backout_extensions
    self.run_extensions(repo, uri, db, backout=True)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/ExtensionsManager.py", line 134, in run_extensions
    self.backout_extension(name, extension, repo, uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/ExtensionsManager.py", line 90, in backout_extension
    extension.backout(repo, uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/extensions/Patches.py", line 258, in backout
    self._do_backout(repo, uri, db, update_statement)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/extensions/__init__.py", line 73, in _do_backout
    exception=ExtensionBackoutError)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/Database.py", line 723, in execute_statement
    raise exception(e)
pycvsanaly2.extensions.ExtensionBackoutError: (1146, "Table 'cvsanaly.patches' doesn't exist")

**Comment by cflewis** [comment]
This should be fixed, please check.

**Comment by linzhp** [comment]
Works now. However, with --backout, cvsanaly exited after backout without refilling the database, is that intended action?

**Comment by cflewis** [comment]
Yes. Backout only backs out. A refill of the database requires a new
command.

## 

Chris Lewis (on cell phone, apologies for typos)
On Apr 23, 2011 12:22 PM, "linzhp" <
reply@reply.github.com>
wrote:
