### ISSUE TITLE
Shelve object can not be read in FilePath

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#86]
Whenever shelve object is read to get file adjacency matrix, CVSAnalY breaks with following error:

Traceback (most recent call last):
  File "./cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/main.py", line 435, in main
    emg.run_extensions(repo, path or uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/ExtensionsManager.py", line 133, in run_extensions
    self.run_extension(name, extension, repo, uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/ExtensionsManager.py", line 76, in run_extension
    extension.run(repo, uri, db)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/extensions/Hunks.py", line 309, in run
    commit_id, repo_id)
  File "/home/linzhp/python/cvsanaly/pycvsanaly2/extensions/FilePaths.py", line 160, in get_path
    adj = self.**dict**['cached_adj'].get(str(commit_id))
  File "/usr/lib/python2.6/shelve.py", line 114, in get
    return self[key]
  File "/usr/lib/python2.6/shelve.py", line 122, in **getitem**
    value = Unpickler(f).load()
AttributeError: 'module' object has no attribute 'Adj'
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored

Also, when I tried in command line to get Adj instance from shelve, the same error occurred:

> > > import shelve
> > > 
> > > s=shelve.open('hello.db',writeback=False)
> > > s
> > > {}
> > > from pycvsanaly2.extensions.FilePaths import FilePaths
> > > adj = FilePaths.Adj()
> > > adj.files=[1,2,3]
> > > adj.adj[1]=3
> > > s['adj']=adj
> > > s
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.6/UserDict.py", line 171, in **repr**
> > >     return repr(dict(self.iteritems()))
> > >   File "/usr/lib/python2.6/UserDict.py", line 110, in iteritems
> > >     yield (k, self[k])
> > >   File "/usr/lib/python2.6/shelve.py", line 122, in **getitem**
> > >     value = Unpickler(f).load()
> > > AttributeError: 'module' object has no attribute 'Adj'
> > > s['adj']
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python2.6/shelve.py", line 122, in **getitem**
> > >     value = Unpickler(f).load()
> > > AttributeError: 'module' object has no attribute 'Adj'

**Comment by linzhp** [comment]
Shelve doesn't support nested classes, per http://stackoverflow.com/questions/4677012/python-cant-pickle-type-x-attribute-lookup-failed

Problem solved by moving Adj out of FilePaths
